[build]
  command = "npm run build"
  publish = "dist"

[functions]
  # Diubah sesuai nama folder Anda
  directory = "cloudnest-backend" 
  directory = "email-sender-service"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200