export * from './HomePage';
export * from './AboutProjectPage';
export * from './AboutDeveloperPage';
export * from './StatusPage';
export * from './SecurityPage';
export * from './LegalPage';
export * from './TryAIPage';
export * from './LoginPage';
export * from './RegisterPage';
export * from './ForgotPasswordPage';
export * from './UpdatePasswordPage';
export * from './EmailVerificationPage';
export * from './AccountSetupPage';
export * from './ProfileSetupPage';
export * from './DashboardPage';
export * from './WelcomePage';
export * from './VerifyNewEmailPage'; 
export * from './StoragePage';
export * from './SettingsPage';
export * from './ProfilePage';
export { default as SettingsSecurityPage } from './SettingsSecurityPage';
export { default as DeviceSettingsPage } from './DeviceSettingsPage';
export { default as IntegrationsPage } from './IntegrationsPage';

